coverage:
  precision: 2
  round: down
  range: '70...100'
  status:
    patch:
      default:
        if_no_uploads: error
        threshold: 50
    changes: true
    project:
      default:
        target: auto
        if_no_uploads: error
        threshold: 2
  ignore:
    - src/helpers/rsa-verifier.js
    - scripts/
    - node_modules/
comment: false
