version: 2.1
orbs:
  ship: auth0/ship@0.3.0
  codecov: codecov/codecov@3
jobs:
  build:
    docker:
      - image: circleci/node:16-browsers
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - ship/node-install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run Tests
          command: npm run ci:test
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - run:
          name: Run ES5 check
          command: npm run test:es-check:es5 && npm run test:es-check:es2015:module
      - codecov/upload
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: build
      - store_artifacts:
          path: junit
      - store_test_results:
          path: junit
workflows:
  build-and-test:
    jobs:
      - build
      - ship/node-publish:
          requires:
            - build
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - master
